OneOf:
  RandomAffine:
    scales: !!python/tuple [0.8, 1.2]
    degrees: !!python/tuple [5, 5]
    isotropic: true
    image_interpolation: linear
    p: 0.5
RandomFlip:
  axes: 2
  flip_probability: 0.5
