title: TFF_TransPosPadUNet3D_EU_seed_46_MIXED
project_dir: '/work/grana_maxillo/results'
seed: 46

wandb:
  mode: online

experiment:
  name: Segmentation

data_loader:
  dataset: /work/grana_maxillo/toothfairy
  training_set: mixed
  preprocessing: configs/preprocessing.yaml
  augmentations: configs/augmentations.yaml
  background_suppression: 0
  batch_size: 16
  labels:
    BACKGROUND: 0
    INSIDE: 1
  num_workers: 4
  patch_shape:
  - 80 
  - 80 
  - 80 
  resize_shape:
  - 168
  - 280
  - 360
  sampler_type: grid
  grid_overlap: 40
  volumes_max: 2100
  volumes_min: 0

model:
  name: MemTransPosPadUNet3D
  n_layers: 4
  n_head: 4
  pos_enc: emb
  mem_len: 128  
  ABS: 1


loss:
  name: Jaccard

lr_scheduler:
  name: OneCycleLR

optimizer:
  learning_rate: 0.0001
  name: Adam
  weight_decay: 0.00005 # 0
  momentum: None

trainer:
  reload: True
  checkpoint: '/work/grana_maxillo/results/TFF_TransPosPadUNet3D_EU_seed_46_MIXED_B844A236F2/checkpoints/best.pth'
  do_train: False
  do_test: True
  do_inference: False
  epochs: 100
