tb_dir: 'Y:\work\runs'
seed: 47
# model configuration
model:
  # model class, supported values: UNet3D, RESNET18, RESNET50
  name: UNet3D
  sharding: 0
# trainer configuration
trainer:
  # path to the checkpoint directory
  checkpoint_path: null
  # skip train or do train?
  do_train: true
  # how many iterations between validations
  validate_after_iters: 2
  # max number of epochs
  epochs: 100

# optimizer configuration
optimizer:
  # type of optimizer. if None, Adam is used by default. possible values: SGD, Adam, None
  name: Adam
  # initial learning rate
  learning_rate: 0.0005
  # weight decay
  weight_decay: 0

# loss function configuration
loss:
  # current supported loss are: BCEWithLogitsLoss, CrossEntropyLoss, DiceLoss
  name:
    - BCEWithLogitsLoss

lr_scheduler:
  # MultiStepLR, null, ...
  name: null
  # factor by which learning rate will be reduced
  factor: 0.1
  milestones:
    - 35
    - 90

data-loader:
  # data loaders configuration
  batch_size: 1
  num_workers: 0
  file_paths: 'Y:\work\datasets\maxillo\VOLUMES\'

  test_patients_id:
    - 5
    - 10

  # create arch line and set to zero all the values out of the arch
  background_suppression: True

  # how many samples we have create from each sample in the original dataset?
  augment_rate: 0
  # percentage before the warmup reach 1
  warm_up_length: 0.35

  # cut so that maxpool does not generate wrong skip features (8 for unet)
  LCM_cut_factor: 32

  # scale the volume in percentage. factor value [0 - 1]
  scale_factor: 0.5


#  labels:
#    UNLABELED: 3
#    BACKGROUND: 2
#    INSIDE: 1
#    CONTOUR: 0

  labels:
    BACKGROUND: 0
    INSIDE: 1
