title: TFF_MemTransPosPadUNet3D_EU_seed_43_TEST
project_dir: '/mnt/beegfs/work/H2020DeciderFicarra/vpipoli/maxillo/results'
seed: 43

wandb:
  mode: online

experiment:
  name: Generation

data_loader:
  dataset: /nas/softechict-nas-2/llumetti/toothfairy
  training_set: null
  preprocessing: configs/preprocessing.yaml
  augmentations: configs/augmentations.yaml
  background_suppression: 0
  batch_size: 2
  labels:
    BACKGROUND: 0
    INSIDE: 1
  mean: 0.08435
  num_workers: 4
  patch_shape:
  - 120
  - 120
  - 120
  resize_shape:
  - 168
  - 280
  - 360
  sampler_type: grid
  grid_overlap: 0
  std: 0.17885
  volumes_max: 2100
  volumes_min: 0
  weights:
  - 0.000703
  - 0.999

model:
  name: MemTransPosPadUNet3D
  n_layers: 4
  n_head: 4
  pos_enc: emb
  mem_len: 10


loss:
  name: Jaccard

lr_scheduler:
  name: OneCycleLR

optimizer:
  learning_rate: 0.0001
  name: Adam
  weight_decay: 0.00005 # 0
  momentum: None

trainer:
  reload: False
  checkpoint: '/mnt/beegfs/work/H2020DeciderFicarra/vpipoli/maxillo/results/TF_MemTransPosPadUNet3D_EU_seed_43_B37E0FDB2A/checkpoints/best.pth'
  do_train: False
  do_test: True
  do_inference: False
  epochs: 100