title: Inference
project_dir: '/homes/llumetti/results'
seed: 49

wandb:
  mode: online

experiment:
  name: Generation

data_loader:
  dataset: /work/grana_maxillo/toothfairy
  training_set: null
  preprocessing: configs/preprocessing.yaml
  augmentations: configs/augmentations.yaml
  background_suppression: 0
  batch_size: 2
  labels:
    BACKGROUND: 0
    INSIDE: 1
  mean: 0.08435
  num_workers: 4
  patch_shape:
  - 120
  - 120
  - 120
  resize_shape:
  - 168
  - 280
  - 360
  sampler_type: grid
  grid_overlap: 60
  std: 0.17885
  volumes_max: 2100
  volumes_min: 0
  weights:
  - 0.000703
  - 0.999

model:
  name: MemTransPosPadUNet3D
  n_layers: 4
  n_head: 4
  pos_enc: emb
  mem_len: 128  
  ABS: True


loss:
  name: Jaccard

lr_scheduler:
  name: OneCycleLR

optimizer:
  learning_rate: 0.0001
  name: Adam
  weight_decay: 0.00005 # 0
  momentum: None

trainer:
  reload: True
  checkpoint: '/mnt/beegfs/work/H2020DeciderFicarra/vpipoli/maxillo/results/TFF_TransPosPadUNet3D_EU_seed_49_D0EE8A062C/checkpoints/best.pth'
  do_train: False
  do_test: False
  do_inference: True
  epochs: 100
