title: canal_generator_train
project_dir: '/homes/llumetti/results'
seed: 47

experiment:
  name: Generation

data_loader:
  dataset: /nas/softechict-nas-1/llumetti/maxillo
  training_set: null
  augmentations: configs/augmentations-half.yaml
  preprocessing: configs/preprocessing.yaml
  background_suppression: 0
  batch_size: 4
  labels:
    BACKGROUND: 0
    INSIDE: 1
  num_workers: 8
  patch_shape:
  - 168
  - 288
  - 192
  resize_shape:
  - 168
  - 288
  - 384
  sampler_type: grid
  grid_overlap: 0
  volumes_max: 2100
  volumes_min: 0

model:
  name: PadUNet3D

loss:
  name: Jaccard

lr_scheduler:
  name: Plateau

optimizer:
  learning_rate: 0.1
  name: SGD

trainer:
  reload: False
  checkpoint: '/nas/softechict-nas-2/mcipriano/results/maxillo/3D/6GK1I26CS_CROP/best.pth'
  do_train: True
  do_test: False
  do_inference: False
  epochs: 100
