title: canal_generator__half
project_dir: '/homes/vpipoli/Maxillo_VP/results'
seed: 47

experiment:
  name: Generation

data_loader:
  dataset: /nas/softechict-nas-1/llumetti/maxillo_resize
  training_set: null
  preprocessing: configs/preprocessing.yaml
  augmentations: configs/augmentations.yaml
  background_suppression: 0
  batch_size: 4
  labels:
    BACKGROUND: 0
    INSIDE: 1
  num_workers: 4
  patch_shape:
  - 56
  - 96
  - 64
  resize_shape:
  - 56
  - 96
  - 64
  sampler_type: grid
  grid_overlap: 0
  overlap_mode: 'crop'

model:
  name: PadUNet3D

loss:
  name:
  - Jaccard

lr_scheduler:
  name: Plateau

optimizer:
  learning_rate: 0.1
  name: SGD

trainer:
  reload: False
  checkpoint: ''
  do_train: True
  do_test: False
  do_inference: False
  epochs: 100
