# CONFIGURATION FOR REMOTE TESTS #

title: 'test_on_00'
tb_dir: '/nas/softechict-nas-2/mcipriano/runs'
seed: 47
# model configuration
model:
  # model class, supported values: UNet3D, RESNET18, RESNET50, Multiscale, transUNet3D, transBTS, PadUNet2D
  name: PadUNet2D

# trainer configuration
trainer:
  # path to the checkpoint directory
  checkpoint_path: null
  # skip train or do train?
  do_train: True
  # possible additional datasets: null, Naive, Generated
  additional_dataset: Naive
  # how many iterations between validations
  validate_after_iters: 2
  # max number of epochs
  epochs: 3

# optimizer configuration
optimizer:
  # type of optimizer. if None, Adam is used by default. possible values: SGD, Adam, None
  name: SGD
  # initial learning rate
  learning_rate: 0.1
  # weight decay
  weight_decay: 0

# loss function configuration
loss:
  # current supported loss are: BCEWithLogitsLoss, CrossEntropyLoss, DiceLoss, Jaccard
  name:
    - Jaccard

lr_scheduler:
  # MultiStepLR, Plateau, null, ...
  name: Plateau

data-loader:
  # data loaders configuration
  batch_size: 32
  num_workers: 0
  # split_filepath: 'split_filepath: '/nas/softechict-nas-2/mcipriano/splits/main_train.json'
  split_filepath: '/homes/mcipriano/projects/alveolar_canal/configs/fake_split.json'

  file_path: '/nas/softechict-nas-2/mcipriano/datasets/maxillo/VOLUMES'
  sparse_path: '/nas/softechict-nas-2/mcipriano/datasets/maxillo/SPARSE'
  augmentations_file: '/homes/mcipriano/sbatch_scripts/augmentations_files/1.yaml'

  # create arch line and set to zero all the values out of the arch
  background_suppression: False

  volumes_max: 2100
  volumes_min: 0

  mean: 0.08435
  std: 0.17885

  weights:
    - 7.03e-04
    - 9.99e-01

  warm_up_length: 0

  # KEEP IN MIND: SCALE RATIOS SHOULD BE AROUND (0.4568, 0.8733, 1)
  resize_shape:
    - 176
    - 336
    - 384

  split_volumes:
    - 1
    - 336
    - 2

  # sparse_dataset: null

  labels:
    BACKGROUND: 0
    INSIDE: 1
