# CONFIGURATION FOR REMOTE TESTS #

title: 'test_on_00'
tb_dir: '/nas/softechict-nas-2/mcipriano/runs'
seed: 47
# model configuration
model:
  # model class, supported values: UNet3D, RESNET18, RESNET50, Multiscale, PositionalUNet3D, transBTS
  name: transBTS

# trainer configuration
trainer:
  # path to the checkpoint directory
  checkpoint_path: null
  # skip train or do train?
  do_train: True
  use_syntetic: False
  # how many iterations between validations
  validate_after_iters: 2
  # max number of epochs
  epochs: 3

# optimizer configuration
optimizer:
  # type of optimizer. if None, Adam is used by default. possible values: SGD, Adam, None
  name: SGD
  # initial learning rate
  learning_rate: 0.1
  # weight decay
  weight_decay: 0

# loss function configuration
loss:
  # current supported loss are: BCEWithLogitsLoss, CrossEntropyLoss, DiceLoss, Jaccard
  name:
    - DiceLoss

lr_scheduler:
  # MultiStepLR, Plateau, null, ...
  name: Plateau

data-loader:
  # data loaders configuration
  batch_size: 1
  num_workers: 0
  # split_filepath: '/homes/mcipriano/projects/alveolar_canal_3Dtraining/configs/splits.json'
  split_filepath: '/homes/mcipriano/projects/alveolar_canal_3Dtraining/configs/fake_split.json'

  file_path: '/nas/softechict-nas-2/mcipriano/datasets/maxillo/VOLUMES'
  sparse_path: '/nas/softechict-nas-2/mcipriano/datasets/maxillo/SPARSE'
  augmentations_file: null

  # create arch line and set to zero all the values out of the arch
  background_suppression: False

  volumes_max: 2100
  volumes_min: 0

  mean: 0.08435
  std: 0.17885

  weights:
    - 7.03e-04
    - 9.99e-01

  warm_up_length: 0

  # KEEP IN MIND: SCALE RATIOS SHOULD BE AROUND (0.4568, 0.8733, 1)
  resize_shape:
    - 136
    - 256
    - 304

  patch_shape:
    - 120
    - 120
    - 120

  samples_per_volume: 8
  sampler_type: grid # valid types: grid, by_label

  # sparse_dataset: null

  labels:
    BACKGROUND: 0
    INSIDE: 1

#  labels:
#    UNLABELED: 3
#    BACKGROUND: 2
#    INSIDE: 1
#    CONTOUR: 0

#  labels:
#    UNLABELED: 2
#    BACKGROUND: 0
#    INSIDE: 1