title: 'test_on_00'
tb_dir: '/nas/softechict-nas-2/mcipriano/runs'
seed: 47
# model configuration
model:
  # model class, supported values: UNet3D, RESNET18, RESNET50
  name: UNet3D
  sharding: False

# trainer configuration
trainer:
  # path to the checkpoint directory
  checkpoint_path: null
  # skip train or do train?
  do_train: true
  # how many iterations between validations
  validate_after_iters: 2
  # max number of epochs
  epochs: 100

# optimizer configuration
optimizer:
  # type of optimizer. if None, Adam is used by default. possible values: SGD, Adam, None
  name: Adam
  # initial learning rate
  learning_rate: 0.0005
  # weight decay
  weight_decay: 0

# loss function configuration
loss:
  # current supported loss are: BCEWithLogitsLoss, CrossEntropyLoss, DiceLoss
  name:
    - BCEWithLogitsLoss
    - DiceLoss

lr_scheduler:
  # MultiStepLR, null, ...
  name: null
  factor: 0.1
  milestones:
    - 150

data-loader:
  # data loaders configuration
  batch_size: 1
  num_workers: 0
  file_paths: '/nas/softechict-nas-2/mcipriano/datasets/maxillo/VOLUMES'

  test_patients_id:
    - 10
    - 20

  # create arch line and set to zero all the values out of the arch
  background_suppression: True

  augment_rate: 0
  warm_up_length: 0

  # cut so that maxpool does not generate wrong skip features (8 for unet)
  LCM_cut_factor: 8

  # scale the volume in percentage. factor value [0 - 1]
  scale_factor: 1

  # average center of the volumes
  cut_index: 0.514

#  labels:
#    UNLABELED: 3
#    BACKGROUND: 2
#    INSIDE: 1
#    CONTOUR: 0

  labels:
    BACKGROUND: 0
    INSIDE: 1
