# CONFIGURATION FOR REMOTE TESTS #

title: 'test_on_00'
tb_dir: '/nas/softechict-nas-2/mcipriano/runs'
seed: 47
# model configuration
model:
  # model class, supported values: UNet3D, RESNET18, RESNET50
  name: UNet3D
  sharding: False

# trainer configuration
trainer:
  # path to the checkpoint directory
  checkpoint_path: null
  # skip train or do train?
  do_train: false
  # how many iterations between validations
  validate_after_iters: 2
  # max number of epochs
  epochs: 100

# optimizer configuration
optimizer:
  # type of optimizer. if None, Adam is used by default. possible values: SGD, Adam, None
  name: Adam
  # initial learning rate
  learning_rate: 0.0005
  # weight decay
  weight_decay: 0

# loss function configuration
loss:
  # current supported loss are: BCEWithLogitsLoss, CrossEntropyLoss, DiceLoss
  name:
    - DiceLoss

lr_scheduler:
  # MultiStepLR, Plateau, null, ...
  name: null
  factor: 0.1
  milestones:
    - 150

data-loader:
  # data loaders configuration
  batch_size: 1
  num_workers: 8
  file_paths: '/nas/softechict-nas-2/mcipriano/datasets/maxillo/VOLUMES'

  # create arch line and set to zero all the values out of the arch
  background_suppression: False

  augment_rate: 0
  warm_up_length: 0
  resize_shape:
    - 80
    - 128
    - 144

#  labels:
#    UNLABELED: 3
#    BACKGROUND: 2
#    INSIDE: 1
#    CONTOUR: 0

  labels:
    BACKGROUND: 0
    INSIDE: 1
