tb_dir: '/nas/softechict-nas-2/mcipriano/runs'

# model configuration
model:
  # model class, supported values: UNet3D
  name: UNet3D

# trainer configuration
trainer:
  # path to the checkpoint directory
  checkpoint_path: null
  # skip train or do train?
  do_train: true
  # how many iterations between validations
  validate_after_iters: 2
  # max number of epochs
  epochs: 100

# optimizer configuration
optimizer:
  # type of optimizer. if None, Adam is used by default. possible values: SGD, Adam, None
  name: Adam
  # initial learning rate
  learning_rate: 0.0005
  # weight decay
  weight_decay: 0

# loss function configuration
loss:
  # current supported loss are: BCEWithLogitsLoss, CrossEntropyLoss, DiceLoss
  name:
    - BCEWithLogitsLoss
    - DiceLoss

lr_scheduler:
  # MultiStepLR, null, ...
  name: null
  # factor by which learning rate will be reduced
  factor: 0.1
  milestones:
    - 35
    - 90

data-loader:
  # data loaders configuration
  batch_size: 1
  num_workers: 0
  file_paths: '/nas/softechict-nas-2/mcipriano/datasets/maxillo/VOLUMES'

  augment_rate: 0
  warm_up_length: 0.35

  # Slice shapes for the network
  do_smart_cut: true
  smart_divisor: 40
  do_rescale: false
  scale_factor: 0.8

  labels:
    UNLABELED: 3
    BACKGROUND: 2
    INSIDE: 1
    CONTOUR: 0

#  labels:
#    BACKGROUND: 0
#    INSIDE: 1
