title: alveolar_canal_pretrain
project_dir: '/homes/llumetti/results'
seed: 47
tensorboard_dir: /homes/llumetti/tensorboard

experiment:
  name: Segmentation

data_loader:
  dataset: /nas/softechict-nas-1/llumetti/maxillo
  training_set: generated # null, generated
  augmentations: configs/augmentations.yaml
  background_suppression: 0
  batch_size: 6
  labels:
    BACKGROUND: 0
    INSIDE: 1
  mean: 0.08435
  num_workers: 4
  patch_shape:
  - 80
  - 80
  - 80
  resize_shape:
  - 168
  - 280
  - 360
  sampler_type: grid
  grid_overlap: 0
  std: 0.17885
  volumes_max: 2100
  volumes_min: 0
  weights:
  - 0.000703
  - 0.999

model:
  name: PosPadUNet3D

loss:
  name: Jaccard

lr_scheduler:
  name: Plateau

optimizer:
  learning_rate: 0.1
  name: SGD

trainer:
  reload: False
  checkpoint: null
  do_train: True
  do_test: False
  do_inference: False
  epochs: 28
